### ISSUE TITLE
CORS / XML erros in the console

### ISSUE THREAD

**Issue by catslug** [sarahjelt/project-one#11]
We're getting CORS / XML errors in the console for both google fonts and the brewery API from the live github pages site. 

Maybe we can make the url's https: instead of http: to fix the issue.

**Comment by sarahjelt** [comment]
Fixed! I'll let you close this since you opened the issue and I guess that's best practice (to make sure the person responding didn't actually misunderstand the issue??)

**Comment by catslug** [comment]
I'm going to close this one and open a new one because this definitely resolves the google fonts link! But now we're getting a CORS error on the brewery API.
